"""
Anthropic OAuth provider — supports both setup-token and Claude Code OAuth.

Two auth methods:
1. setup-token (default) - Generated by `claude setup-token`, expires in ~24h
2. claude-code - Reads OAuth credentials from ~/.claude/.credentials.json with auto-refresh

Usage in config.json:
    {
        "providers": {
            "anthropic": {
                "authMethod": "claude-code"
            }
        }
    }
"""

import json
import logging
import time
from pathlib import Path
from typing import Any

import anthropic
import httpx

from nanobot.providers.base import LLMProvider, LLMResponse, ToolCallRequest

logger = logging.getLogger(__name__)

# Setup-token validation (legacy)
SETUP_TOKEN_PREFIX = "sk-ant-oat01-"
SETUP_TOKEN_MIN_LENGTH = 80

# Claude Code OAuth constants
CLAUDE_CODE_CREDENTIALS_PATH = Path.home() / ".claude" / ".credentials.json"
CLAUDE_CODE_CLIENT_ID = "9d1c250a-e61b-44d9-88ed-5944d1962f5e"
CLAUDE_CODE_TOKEN_URL = "https://platform.claude.com/v1/oauth/token"
CLAUDE_CODE_SCOPES = "user:inference user:sessions:claude_code user:mcp_servers"
OAUTH_BETA_HEADER = "oauth-2025-04-20"
REFRESH_MARGIN_SECONDS = 300  # Refresh 5 minutes before expiry


def read_claude_code_credentials() -> dict[str, Any] | None:
    """
    Read Claude Code OAuth credentials from ~/.claude/.credentials.json.

    Returns the claudeAiOauth dict with keys:
    - accessToken (str)
    - refreshToken (str)
    - expiresAt (int, timestamp in milliseconds)
    - scopes (list[str])
    - subscriptionType (str | None)
    - rateLimitTier (str | None)

    Returns None if file doesn't exist or claudeAiOauth is missing.
    """
    if not CLAUDE_CODE_CREDENTIALS_PATH.exists():
        logger.warning(
            "Claude Code credentials file not found at %s. "
            "Run `claude auth login` first.",
            CLAUDE_CODE_CREDENTIALS_PATH,
        )
        return None

    try:
        with open(CLAUDE_CODE_CREDENTIALS_PATH, "r", encoding="utf-8") as f:
            data = json.load(f)

        oauth_creds = data.get("claudeAiOauth")
        if not oauth_creds:
            logger.warning("No claudeAiOauth field found in credentials file")
            return None

        # Validate required fields
        required = ["accessToken", "refreshToken", "expiresAt"]
        missing = [k for k in required if k not in oauth_creds]
        if missing:
            logger.error("Missing required fields in claudeAiOauth: %s", missing)
            return None

        return oauth_creds

    except json.JSONDecodeError as e:
        logger.error("Failed to parse credentials file: %s", e)
        return None
    except Exception as e:
        logger.error("Error reading credentials file: %s", e)
        return None


def needs_refresh(expires_at_ms: int) -> bool:
    """Check if access token needs refresh (< 5 minutes until expiry)."""
    now_ms = int(time.time() * 1000)
    margin_ms = REFRESH_MARGIN_SECONDS * 1000
    return (expires_at_ms - now_ms) < margin_ms


def validate_setup_token(token: str) -> str | None:
    """Validate setup-token format. Returns error message or None if valid."""
    token = token.strip()
    if not token:
        return "Setup-token is empty"
    if not token.startswith(SETUP_TOKEN_PREFIX):
        return f"Setup-token must start with {SETUP_TOKEN_PREFIX}"
    if len(token) < SETUP_TOKEN_MIN_LENGTH:
        return f"Setup-token too short (min {SETUP_TOKEN_MIN_LENGTH} chars)"
    return None


class AnthropicOAuthProvider(LLMProvider):
    """
    LLM provider using Anthropic API with OAuth setup-token.

    Uses `Authorization: Bearer <token>` instead of `x-api-key`.
    Requires `anthropic` SDK: pip install anthropic
    """

    def __init__(
        self,
        setup_token: str,
        default_model: str = "claude-sonnet-4-5-20250929",
    ):
        super().__init__(api_key=None, api_base=None)
        self.setup_token = setup_token.strip()
        self.default_model = default_model

        error = validate_setup_token(self.setup_token)
        if error:
            raise ValueError(f"Invalid setup-token: {error}")

        # Create Anthropic client with OAuth auth_token (Bearer), not api_key (x-api-key)
        self.client = anthropic.AsyncAnthropic(
            auth_token=self.setup_token,
            default_headers={
                "anthropic-beta": "oauth-2025-04-20",
            },
        )

    async def chat(
        self,
        messages: list[dict[str, Any]],
        tools: list[dict[str, Any]] | None = None,
        model: str | None = None,
        max_tokens: int = 4096,
        temperature: float = 0.7,
    ) -> LLMResponse:
        """Send a chat completion request via Anthropic API with OAuth token."""
        model = model or self.default_model
        # Strip provider prefix if present (e.g. "anthropic/claude-sonnet-4-5")
        if "/" in model:
            model = model.split("/", 1)[1]

        system_parts = []
        api_messages = []

        for msg in messages:
            role = msg.get("role", "")
            content = msg.get("content", "")

            if role == "system":
                system_parts.append(content)
            elif role == "user":
                tool_call_id = msg.get("tool_call_id")
                if tool_call_id:
                    api_messages.append({
                        "role": "user",
                        "content": [
                            {
                                "type": "tool_result",
                                "tool_use_id": tool_call_id,
                                "content": content,
                            }
                        ],
                    })
                else:
                    api_messages.append({"role": "user", "content": content})
            elif role == "assistant":
                tool_calls = msg.get("tool_calls", [])
                if tool_calls:
                    blocks: list[dict[str, Any]] = []
                    if content:
                        blocks.append({"type": "text", "text": content})
                    for tc in tool_calls:
                        blocks.append({
                            "type": "tool_use",
                            "id": tc.get("id", ""),
                            "name": tc.get("name", ""),
                            "input": tc.get("arguments", {}),
                        })
                    api_messages.append({"role": "assistant", "content": blocks})
                else:
                    api_messages.append({"role": "assistant", "content": content})
            elif role == "tool":
                tool_call_id = msg.get("tool_call_id", "")
                api_messages.append({
                    "role": "user",
                    "content": [
                        {
                            "type": "tool_result",
                            "tool_use_id": tool_call_id,
                            "content": content,
                        }
                    ],
                })

        # Build kwargs
        kwargs: dict[str, Any] = {
            "model": model,
            "messages": api_messages,
            "max_tokens": max_tokens,
            "temperature": temperature,
        }

        if system_parts:
            kwargs["system"] = "\n\n".join(system_parts)

        if tools:
            kwargs["tools"] = self._convert_tools(tools)

        try:
            response = await self.client.messages.create(**kwargs)
            return self._parse_response(response)
        except anthropic.AuthenticationError as e:
            logger.error("Setup-token authentication failed: %s", e)
            return LLMResponse(
                content=f"Authentication failed (setup-token may be expired): {e}",
                finish_reason="error",
            )
        except anthropic.PermissionDeniedError as e:
            logger.error("Setup-token permission denied: %s", e)
            return LLMResponse(
                content=f"Permission denied (setup-token may be blocked): {e}",
                finish_reason="error",
            )
        except anthropic.RateLimitError as e:
            logger.error("Anthropic rate limit: %s", e)
            return LLMResponse(
                content=f"Rate limit exceeded: {e}",
                finish_reason="error",
            )
        except anthropic.APIError as e:
            logger.error("Anthropic API error: %s", e)
            return LLMResponse(
                content=f"Error calling Anthropic API: {e}",
                finish_reason="error",
            )

    def _convert_tools(self, tools: list[dict[str, Any]]) -> list[dict[str, Any]]:
        """Convert OpenAI-format tools to Anthropic format."""
        anthropic_tools = []
        for tool in tools:
            if tool.get("type") != "function":
                continue
            func = tool.get("function", {})
            anthropic_tools.append({
                "name": func.get("name", ""),
                "description": func.get("description", ""),
                "input_schema": func.get("parameters", {"type": "object", "properties": {}}),
            })
        return anthropic_tools

    def _parse_response(self, response: anthropic.types.Message) -> LLMResponse:
        """Parse Anthropic API response into standard LLMResponse."""
        content_parts = []
        tool_calls = []

        for block in response.content:
            if block.type == "text":
                content_parts.append(block.text)
            elif block.type == "tool_use":
                tool_calls.append(ToolCallRequest(
                    id=block.id,
                    name=block.name,
                    arguments=block.input if isinstance(block.input, dict) else {},
                ))

        finish_reason = "stop"
        if response.stop_reason == "tool_use":
            finish_reason = "tool_calls"
        elif response.stop_reason == "max_tokens":
            finish_reason = "length"

        usage = {}
        if response.usage:
            usage = {
                "prompt_tokens": response.usage.input_tokens,
                "completion_tokens": response.usage.output_tokens,
                "total_tokens": response.usage.input_tokens + response.usage.output_tokens,
            }

        return LLMResponse(
            content="\n".join(content_parts) if content_parts else None,
            tool_calls=tool_calls,
            finish_reason=finish_reason,
            usage=usage,
        )

    def get_default_model(self) -> str:
        return self.default_model
